authors:
  DanielHabenicht:
    name: Daniel Habenicht        # Author name
    description: This is my about page. Some more info will be coming soon. # Author description
    avatar: /assets/logo.png         # Author avatar
    url: https://aquiver.de            # Author website URL