authors:
  DanielHabenicht:
    name: Daniel Habenicht        # Author name
    description: That's me! # Author description
    avatar: /assets/logo.png         # Author avatar
    url: https://aquiver.de            # Author website URL