name: ci
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install pngquant -y
      - run: pip install git+https://${GH_TOKEN}@github.com/DanielHabenicht/fork.mkdocs-material-insiders.git mkdocs-material[imaging]
      # Fix https://github.com/squidfunk/mkdocs-material/issues/6983
      - run: | 
          export FONT_FAMILY=Roboto
          mkdir -p .cache/plugin/social/fonts/$FONT_FAMILY
          cd workaround
          unzip $FONT_FAMILY.zip 
          for f in *.ttf; do mv -f "$f" "$(echo "$f" | sed s/Roboto-//)"; done
          mv -f ./*.ttf ../.cache/plugin/social/fonts/$FONT_FAMILY
      - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
